import './globals.scss'
import type { Metadata } from 'next'
import { Shippori_Mincho_B1 } from 'next/font/google'

const shippori_mincho_b1 = Shippori_Mincho_B1({ 
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={shippori_mincho_b1.className}>{children}</body>
    </html>
  )
}
